import { PrismaClient } from '@prisma/client';

async function seedSubStates() {
  const prisma = new PrismaClient();

  try {
    // Sub States to be seeded
    const subStatesData: {
      id: number;
      state_id: number;
      sub_state_name: string;
    }[] = [
      { id: 1, state_id: 47, sub_state_name: 'Wajir East' },
      { id: 2, state_id: 25, sub_state_name: 'Samburu East' },
      { id: 3, state_id: 24, sub_state_name: 'Laikipia West' },
      { id: 4, state_id: 26, sub_state_name: 'Borabu' },
      { id: 5, state_id: 10, sub_state_name: 'Masinga' },
      { id: 6, state_id: 5, sub_state_name: 'Suna West' },
      { id: 7, state_id: 36, sub_state_name: 'Njoro' },
      { id: 8, state_id: 47, sub_state_name: 'Tarbaj' },
      { id: 9, state_id: 5, sub_state_name: 'Uriri' },
      { id: 10, state_id: 17, sub_state_name: 'Lari' },
      { id: 11, state_id: 46, sub_state_name: 'Fafi' },
      { id: 12, state_id: 31, sub_state_name: 'Embakasi Central' },
      { id: 13, state_id: 29, sub_state_name: 'Kipipiri' },
      { id: 14, state_id: 28, sub_state_name: 'Moyale' },
      { id: 15, state_id: 1, sub_state_name: 'Narok West' },
      { id: 16, state_id: 20, sub_state_name: 'Ugenya' },
      { id: 17, state_id: 15, sub_state_name: 'Webuye East' },
      { id: 18, state_id: 17, sub_state_name: 'Kiambu' },
      { id: 19, state_id: 31, sub_state_name: 'Dagoretti South' },
      { id: 20, state_id: 31, sub_state_name: 'Mathare' },
      { id: 21, state_id: 1, sub_state_name: 'Narok South' },
      { id: 22, state_id: 5, sub_state_name: 'Nyatike' },
      { id: 23, state_id: 37, sub_state_name: 'Cherangany' },
      { id: 24, state_id: 31, sub_state_name: 'Embakasi East' },
      { id: 25, state_id: 47, sub_state_name: 'Wajir North' },
      { id: 26, state_id: 35, sub_state_name: 'Bomet East' },
      { id: 27, state_id: 38, sub_state_name: 'Kitutu Chache South' },
      { id: 28, state_id: 17, sub_state_name: 'Kabete' },
      { id: 29, state_id: 42, sub_state_name: 'Kajiado East' },
      { id: 30, state_id: 36, sub_state_name: 'Molo' },
      { id: 31, state_id: 6, sub_state_name: 'Nyali' },
      { id: 32, state_id: 18, sub_state_name: 'Butula' },
      { id: 33, state_id: 36, sub_state_name: 'Nakuru Town East' },
      { id: 34, state_id: 44, sub_state_name: 'South Imenti' },
      { id: 35, state_id: 7, sub_state_name: 'Kitui Rural' },
      { id: 36, state_id: 19, sub_state_name: 'Kibwezi East' },
      { id: 37, state_id: 24, sub_state_name: 'Laikipia North' },
      { id: 38, state_id: 21, sub_state_name: 'Matuga' },
      { id: 39, state_id: 17, sub_state_name: 'Thika Town' },
      { id: 40, state_id: 17, sub_state_name: 'Gatundu North' },
      { id: 41, state_id: 46, sub_state_name: 'Lagdera' },
      { id: 42, state_id: 23, sub_state_name: 'Kigumo' },
      { id: 43, state_id: 6, sub_state_name: 'Likoni' },
      { id: 44, state_id: 17, sub_state_name: 'Kikuyu' },
      { id: 45, state_id: 20, sub_state_name: 'Ugunja' },
      { id: 46, state_id: 9, sub_state_name: 'Kilifi South' },
      { id: 47, state_id: 44, sub_state_name: 'Igembe South' },
      { id: 48, state_id: 36, sub_state_name: 'Gilgil' },
      { id: 49, state_id: 42, sub_state_name: 'Kajiado Central' },
      { id: 50, state_id: 22, sub_state_name: 'Hamisi' },
      { id: 51, state_id: 46, sub_state_name: 'Dadaab' },
      { id: 52, state_id: 35, sub_state_name: 'Chepalungu' },
      { id: 53, state_id: 37, sub_state_name: 'Kwanza' },
      { id: 54, state_id: 6, sub_state_name: 'Mvita' },
      { id: 55, state_id: 4, sub_state_name: 'Kipkelion East' },
      { id: 56, state_id: 33, sub_state_name: 'Ikolomani' },
      { id: 57, state_id: 19, sub_state_name: 'Makueni' },
      { id: 58, state_id: 34, sub_state_name: 'Runyenjes' },
      { id: 59, state_id: 4, sub_state_name: 'Ainamoi' },
      { id: 60, state_id: 40, sub_state_name: 'Gichugu' },
      { id: 61, state_id: 1, sub_state_name: 'Kilgoris' },
      { id: 62, state_id: 2, sub_state_name: 'Turkana West' },
      { id: 63, state_id: 9, sub_state_name: 'Kaloleni' },
      { id: 64, state_id: 45, sub_state_name: 'Nyakach' },
      { id: 65, state_id: 8, sub_state_name: 'Nandi Hills' },
      { id: 66, state_id: 33, sub_state_name: 'Shinyalu' },
      { id: 67, state_id: 10, sub_state_name: 'Machakos Town' },
      { id: 68, state_id: 39, sub_state_name: 'Tharaka' },
      { id: 69, state_id: 43, sub_state_name: 'Homa Bay Town' },
      { id: 70, state_id: 37, sub_state_name: 'Kiminini' },
      { id: 71, state_id: 19, sub_state_name: 'Kaiti' },
      { id: 72, state_id: 31, sub_state_name: 'Langata' },
      { id: 73, state_id: 36, sub_state_name: 'Rongai' },
      { id: 74, state_id: 3, sub_state_name: 'Nyeri Town' },
      { id: 75, state_id: 15, sub_state_name: 'Webuye West' },
      { id: 76, state_id: 33, sub_state_name: 'Khwisero' },
      { id: 77, state_id: 44, sub_state_name: 'Tigania West' },
      { id: 78, state_id: 15, sub_state_name: 'Kimilili' },
      { id: 79, state_id: 20, sub_state_name: 'Bondo' },
      { id: 80, state_id: 7, sub_state_name: 'Kitui East' },
      { id: 81, state_id: 21, sub_state_name: 'Msambweni' },
      { id: 82, state_id: 6, sub_state_name: 'Changamwe' },
      { id: 83, state_id: 43, sub_state_name: 'Kasipul' },
      { id: 84, state_id: 30, sub_state_name: 'Mwatate' },
      { id: 85, state_id: 34, sub_state_name: 'Mbeere South' },
      { id: 86, state_id: 15, sub_state_name: 'Tongaren' },
      { id: 87, state_id: 3, sub_state_name: 'Tetu' },
      { id: 88, state_id: 31, sub_state_name: 'Starehe' },
      { id: 89, state_id: 31, sub_state_name: 'Makadara' },
      { id: 90, state_id: 19, sub_state_name: 'Mbooni' },
      { id: 91, state_id: 25, sub_state_name: 'Samburu North' },
      { id: 92, state_id: 23, sub_state_name: 'Maragwa' },
      { id: 93, state_id: 10, sub_state_name: 'Kathiani' },
      { id: 94, state_id: 35, sub_state_name: 'Konoin' },
      { id: 95, state_id: 11, sub_state_name: 'Banissa' },
      { id: 96, state_id: 35, sub_state_name: 'Bomet Central' },
      { id: 97, state_id: 23, sub_state_name: 'Kangema' },
      { id: 98, state_id: 10, sub_state_name: 'Yatta' },
      { id: 99, state_id: 1, sub_state_name: 'Narok East' },
      { id: 100, state_id: 47, sub_state_name: 'Wajir South' },
      { id: 101, state_id: 12, sub_state_name: 'Lamu West' },
      { id: 102, state_id: 30, sub_state_name: 'Taveta' },
      { id: 103, state_id: 33, sub_state_name: 'Lurambi' },
      { id: 104, state_id: 44, sub_state_name: 'Igembe Central' },
      { id: 105, state_id: 20, sub_state_name: 'Rarieda' },
      { id: 106, state_id: 34, sub_state_name: 'Manyatta' },
      { id: 107, state_id: 7, sub_state_name: 'Kitui Central' },
      { id: 108, state_id: 11, sub_state_name: 'Lafey' },
      { id: 109, state_id: 27, sub_state_name: 'Sigor' },
      { id: 110, state_id: 18, sub_state_name: 'Nambale' },
      { id: 111, state_id: 3, sub_state_name: 'Othaya' },
      { id: 112, state_id: 22, sub_state_name: 'Sabatia' },
      { id: 113, state_id: 14, sub_state_name: 'Baringo North' },
      { id: 114, state_id: 20, sub_state_name: 'Alego Usonga' },
      { id: 115, state_id: 3, sub_state_name: 'Mukurweini' },
      { id: 116, state_id: 9, sub_state_name: 'Malindi' },
      { id: 117, state_id: 31, sub_state_name: 'Kasarani' },
      { id: 118, state_id: 36, sub_state_name: 'Nakuru Town West' },
      { id: 119, state_id: 18, sub_state_name: 'Funyula' },
      { id: 120, state_id: 2, sub_state_name: 'Turkana South' },
      { id: 121, state_id: 38, sub_state_name: 'Bonchari' },
      { id: 122, state_id: 39, sub_state_name: 'Chuka/Igambangombe' },
      { id: 123, state_id: 46, sub_state_name: 'Balambala' },
      { id: 124, state_id: 27, sub_state_name: 'Kapenguria' },
      { id: 125, state_id: 44, sub_state_name: 'Buuri' },
      { id: 126, state_id: 17, sub_state_name: 'Kiambaa' },
      { id: 127, state_id: 15, sub_state_name: 'Bumula' },
      { id: 128, state_id: 38, sub_state_name: 'Bobasi' },
      { id: 129, state_id: 8, sub_state_name: 'Chesumei' },
      { id: 130, state_id: 45, sub_state_name: 'Muhoroni' },
      { id: 131, state_id: 26, sub_state_name: 'North Mugirango' },
      { id: 132, state_id: 38, sub_state_name: 'Nyaribari Chache' },
      { id: 133, state_id: 43, sub_state_name: 'Mbita' },
      { id: 134, state_id: 7, sub_state_name: 'Mwingi North' },
      { id: 135, state_id: 4, sub_state_name: 'Bureti' },
      { id: 136, state_id: 15, sub_state_name: 'Kabuchai' },
      { id: 137, state_id: 8, sub_state_name: 'Tinderet' },
      { id: 138, state_id: 5, sub_state_name: 'Kuria West' },
      { id: 139, state_id: 18, sub_state_name: 'Budalangi' },
      { id: 140, state_id: 6, sub_state_name: 'Kisauni' },
      { id: 141, state_id: 31, sub_state_name: 'Roysambu' },
      { id: 142, state_id: 29, sub_state_name: 'Ol Kalou' },
      { id: 143, state_id: 38, sub_state_name: 'Kitutu Chache North' },
      { id: 144, state_id: 9, sub_state_name: 'Magarini' },
      { id: 145, state_id: 7, sub_state_name: 'Mwingi Central' },
      { id: 146, state_id: 40, sub_state_name: 'Mwea' },
      { id: 147, state_id: 31, sub_state_name: 'Ruaraka' },
      { id: 148, state_id: 8, sub_state_name: 'Aldai' },
      { id: 149, state_id: 5, sub_state_name: 'Suna East' },
      { id: 150, state_id: 30, sub_state_name: 'Voi' },
      { id: 151, state_id: 11, sub_state_name: 'Mandera West' },
      { id: 152, state_id: 34, sub_state_name: 'Mbeere North' },
      { id: 153, state_id: 1, sub_state_name: 'Narok North' },
      { id: 154, state_id: 23, sub_state_name: 'Gatanga' },
      { id: 155, state_id: 38, sub_state_name: 'South Mugirango' },
      { id: 156, state_id: 45, sub_state_name: 'Kisumu Central' },
      { id: 157, state_id: 47, sub_state_name: 'Wajir West' },
      { id: 158, state_id: 32, sub_state_name: 'Keiyo South' },
      { id: 159, state_id: 32, sub_state_name: 'Keiyo North' },
      { id: 160, state_id: 43, sub_state_name: 'Rangwe' },
      { id: 161, state_id: 2, sub_state_name: 'Loima' },
      { id: 162, state_id: 10, sub_state_name: 'Matungulu' },
      { id: 163, state_id: 41, sub_state_name: 'Isiolo North' },
      { id: 164, state_id: 33, sub_state_name: 'Mumias West' },
      { id: 165, state_id: 43, sub_state_name: 'Kabondo Kasipul' },
      { id: 166, state_id: 46, sub_state_name: 'Garissa Township' },
      { id: 167, state_id: 42, sub_state_name: 'Kajiado South' },
      { id: 168, state_id: 2, sub_state_name: 'Turkana Central' },
      { id: 169, state_id: 25, sub_state_name: 'Samburu West' },
      { id: 170, state_id: 36, sub_state_name: 'Bahati' },
      { id: 171, state_id: 43, sub_state_name: 'Ndhiwa' },
      { id: 172, state_id: 11, sub_state_name: 'Mandera East' },
      { id: 173, state_id: 23, sub_state_name: 'Kandara' },
      { id: 174, state_id: 41, sub_state_name: 'Isiolo South' },
      { id: 175, state_id: 20, sub_state_name: 'Gem' },
      { id: 176, state_id: 17, sub_state_name: 'Ruiru' },
      { id: 177, state_id: 33, sub_state_name: 'Navakholo' },
      { id: 178, state_id: 37, sub_state_name: 'Saboti' },
      { id: 179, state_id: 37, sub_state_name: 'Endebess' },
      { id: 180, state_id: 21, sub_state_name: 'Lunga Lunga' },
      { id: 181, state_id: 13, sub_state_name: 'Kesses' },
      { id: 182, state_id: 8, sub_state_name: 'Mosop' },
      { id: 183, state_id: 44, sub_state_name: 'North Imenti' },
      { id: 184, state_id: 23, sub_state_name: 'Kiharu' },
      { id: 185, state_id: 26, sub_state_name: 'West Mugirango' },
      { id: 186, state_id: 5, sub_state_name: 'Kuria East' },
      { id: 187, state_id: 16, sub_state_name: 'Bura' },
      { id: 188, state_id: 9, sub_state_name: 'Ganze' },
      { id: 189, state_id: 26, sub_state_name: 'Kitutu Masaba' },
      { id: 190, state_id: 22, sub_state_name: 'Vihiga' },
      { id: 191, state_id: 30, sub_state_name: 'Wundanyi' },
      { id: 192, state_id: 29, sub_state_name: 'Kinangop' },
      { id: 193, state_id: 31, sub_state_name: 'Kibra' },
      { id: 194, state_id: 47, sub_state_name: 'Eldas' },
      { id: 195, state_id: 12, sub_state_name: 'Lamu East' },
      { id: 196, state_id: 16, sub_state_name: 'Galole' },
      { id: 197, state_id: 45, sub_state_name: 'Kisumu West' },
      { id: 198, state_id: 7, sub_state_name: 'Mwingi West' },
      { id: 199, state_id: 6, sub_state_name: 'Jomvu' },
      { id: 200, state_id: 45, sub_state_name: 'Kisumu East' },
      { id: 201, state_id: 18, sub_state_name: 'Teso North' },
      { id: 202, state_id: 36, sub_state_name: 'Kuresoi North' },
      { id: 203, state_id: 3, sub_state_name: 'Kieni' },
      { id: 204, state_id: 31, sub_state_name: 'Embakasi West' },
      { id: 205, state_id: 36, sub_state_name: 'Subukia' },
      { id: 206, state_id: 33, sub_state_name: 'Likuyani' },
      { id: 207, state_id: 35, sub_state_name: 'Sotik' },
      { id: 208, state_id: 31, sub_state_name: 'Embakasi South' },
      { id: 209, state_id: 32, sub_state_name: 'Marakwet East' },
      { id: 210, state_id: 11, sub_state_name: 'Mandera South' },
      { id: 211, state_id: 43, sub_state_name: 'Suba' },
      { id: 212, state_id: 17, sub_state_name: 'Githunguri' },
      { id: 213, state_id: 22, sub_state_name: 'Luanda' },
      { id: 214, state_id: 32, sub_state_name: 'Marakwet West' },
      { id: 215, state_id: 22, sub_state_name: 'Emuhaya' },
      { id: 216, state_id: 8, sub_state_name: 'Emgwen' },
      { id: 217, state_id: 7, sub_state_name: 'Kitui West' },
      { id: 218, state_id: 5, sub_state_name: 'Rongo' },
      { id: 219, state_id: 36, sub_state_name: 'Kuresoi South' },
      { id: 220, state_id: 3, sub_state_name: 'Mathira' },
      { id: 221, state_id: 45, sub_state_name: 'Nyando' },
      { id: 222, state_id: 13, sub_state_name: 'Kapseret' },
      { id: 223, state_id: 18, sub_state_name: 'Teso South' },
      { id: 224, state_id: 31, sub_state_name: 'Westlands' },
      { id: 225, state_id: 2, sub_state_name: 'Turkana East' },
      { id: 226, state_id: 13, sub_state_name: 'Moiben' },
      { id: 227, state_id: 38, sub_state_name: 'Nyaribari Masaba' },
      { id: 228, state_id: 33, sub_state_name: 'Lugari' },
      { id: 229, state_id: 28, sub_state_name: 'Saku' },
      { id: 230, state_id: 16, sub_state_name: 'Garsen' },
      { id: 231, state_id: 17, sub_state_name: 'Gatundu South' },
      { id: 232, state_id: 40, sub_state_name: 'Ndia' },
      { id: 233, state_id: 4, sub_state_name: 'Kipkelion West' },
      { id: 234, state_id: 28, sub_state_name: 'Laisamis' },
      { id: 235, state_id: 19, sub_state_name: 'Kibwezi West' },
      { id: 236, state_id: 43, sub_state_name: 'Karachuonyo' },
      { id: 237, state_id: 42, sub_state_name: 'Kajiado West' },
      { id: 238, state_id: 19, sub_state_name: 'Kilome' },
      { id: 239, state_id: 39, sub_state_name: 'Maara' },
      { id: 240, state_id: 10, sub_state_name: 'Mavoko' },
      { id: 241, state_id: 4, sub_state_name: 'Sigowet Soin' },
      { id: 242, state_id: 4, sub_state_name: 'Belgut' },
      { id: 243, state_id: 17, sub_state_name: 'Limuru' },
      { id: 244, state_id: 11, sub_state_name: 'Mandera North' },
      { id: 245, state_id: 14, sub_state_name: 'Eldama Ravine' },
      { id: 246, state_id: 27, sub_state_name: 'Pokot South' },
      { id: 247, state_id: 15, sub_state_name: 'Sirisia' },
      { id: 248, state_id: 44, sub_state_name: 'Central Imenti' },
      { id: 249, state_id: 33, sub_state_name: 'Mumias East' },
      { id: 250, state_id: 31, sub_state_name: 'Kamukunji' },
      { id: 251, state_id: 2, sub_state_name: 'Turkana North' },
      { id: 252, state_id: 33, sub_state_name: 'Malava' },
      { id: 253, state_id: 29, sub_state_name: 'Ol Jorok' },
      { id: 254, state_id: 13, sub_state_name: 'Turbo' },
      { id: 255, state_id: 33, sub_state_name: 'Matungu' },
      { id: 256, state_id: 46, sub_state_name: 'Ijara' },
      { id: 257, state_id: 9, sub_state_name: 'Kilifi North' },
      { id: 258, state_id: 33, sub_state_name: 'Butere' },
      { id: 259, state_id: 9, sub_state_name: 'Rabai' },
      { id: 260, state_id: 44, sub_state_name: 'Igembe North' },
      { id: 261, state_id: 44, sub_state_name: 'Tigania East' },
      { id: 262, state_id: 5, sub_state_name: 'Awendo' },
      { id: 263, state_id: 14, sub_state_name: 'Mogotio' },
      { id: 264, state_id: 14, sub_state_name: 'Baringo Central' },
      { id: 265, state_id: 10, sub_state_name: 'Mwala' },
      { id: 266, state_id: 21, sub_state_name: 'Kinango' },
      { id: 267, state_id: 23, sub_state_name: 'Mathioya' },
      { id: 268, state_id: 14, sub_state_name: 'Tiaty' },
      { id: 269, state_id: 31, sub_state_name: 'Embakasi North' },
      { id: 270, state_id: 31, sub_state_name: 'Dagoretti North' },
      { id: 271, state_id: 36, sub_state_name: 'Naivasha' },
      { id: 272, state_id: 18, sub_state_name: 'Matayos' },
      { id: 273, state_id: 38, sub_state_name: 'Bomachoge Borabu' },
      { id: 274, state_id: 7, sub_state_name: 'Kitui South' },
      { id: 275, state_id: 42, sub_state_name: 'Kajiado North' },
      { id: 276, state_id: 15, sub_state_name: 'Mount Elgon' },
      { id: 277, state_id: 40, sub_state_name: 'Kirinyaga Central' },
      { id: 278, state_id: 38, sub_state_name: 'Bomachoge Chache' },
      { id: 279, state_id: 13, sub_state_name: 'Ainabkoi' },
      { id: 280, state_id: 13, sub_state_name: 'Soy' },
      { id: 281, state_id: 14, sub_state_name: 'Baringo South' },
      { id: 282, state_id: 15, sub_state_name: 'Kanduyi' },
      { id: 283, state_id: 29, sub_state_name: 'Ndaragwa' },
      { id: 284, state_id: 28, sub_state_name: 'North Horr' },
      { id: 285, state_id: 27, sub_state_name: 'Kacheliba' },
      { id: 286, state_id: 24, sub_state_name: 'Laikipia East' },
      { id: 287, state_id: 1, sub_state_name: 'Emurua Dikirr' },
      { id: 288, state_id: 17, sub_state_name: 'Juja' },
      { id: 289, state_id: 45, sub_state_name: 'Seme' },
      { id: 290, state_id: 10, sub_state_name: 'Kangundo' },
    ];

    // Insert the sub_states into the database
    await prisma.subStates.createMany({
      data: subStatesData,
    });

    console.log('Sub States seeded successfully.');
  } catch (error) {
    console.log('Error seeding Sub States:', error);
  } finally {
    await prisma.$disconnect();
  }
}

seedSubStates();
