name: Continuous Integration

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install
        npm install ajv@^6.9.1  # Install ajv peer dependency explicitly

    - name: Build
      run: npm run build

    - name: Linting Code
      run: npm run lint

    - name: Run E2E tests
      run: npm run test:e2e
